const COUNTRY_LANGUAGES = [
  { country: "Afghanistan", languages: [["ps", "پښتو", "Pashto"], ["fa", "دری", "Dari"]] },
  { country: "Albania", languages: [["sq", "Shqip", "Albanian"]] },
  { country: "Algeria", languages: [["ar", "العربية", "Arabic"], ["zgh", "ⵜⴰⵎⴰⵣⵉⵖⵜ", "Tamazight"]] },
  { country: "Andorra", languages: [["ca", "Català", "Catalan"]] },
  { country: "Angola", languages: [["pt", "Português", "Portuguese"]] },
  { country: "Antigua and Barbuda", languages: [["en", "English", "English"]] },
  { country: "Argentina", languages: [["es", "Español", "Spanish"]] },
  { country: "Armenia", languages: [["hy", "Հայերեն", "Armenian"]] },
  { country: "Australia", languages: [["en", "English", "English"]] },
  { country: "Austria", languages: [["de", "Deutsch", "German"]] },
  { country: "Azerbaijan", languages: [["az", "Azərbaycan", "Azerbaijani"]] },
  { country: "Bahamas", languages: [["en", "English", "English"]] },
  { country: "Bahrain", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Bangladesh", languages: [["bn", "বাংলা", "Bengali"]] },
  { country: "Barbados", languages: [["en", "English", "English"]] },
  { country: "Belarus", languages: [["be", "Беларуская", "Belarusian"], ["ru", "Русский", "Russian"]] },
  { country: "Belgium", languages: [["nl", "Nederlands", "Dutch"], ["fr", "Français", "French"], ["de", "Deutsch", "German"]] },
  { country: "Belize", languages: [["en", "English", "English"]] },
  { country: "Benin", languages: [["fr", "Français", "French"]] },
  { country: "Bhutan", languages: [["dz", "རྫོང་ཁ", "Dzongkha"]] },
  { country: "Bolivia", languages: [["es", "Español", "Spanish"], ["qu", "Runa Simi", "Quechua"], ["ay", "Aymar aru", "Aymara"], ["gn", "Avañe’ẽ", "Guarani"]] },
  { country: "Bosnia and Herzegovina", languages: [["bs", "Bosanski", "Bosnian"], ["hr", "Hrvatski", "Croatian"], ["sr", "Српски", "Serbian"]] },
  { country: "Botswana", languages: [["en", "English", "English"], ["tn", "Setswana", "Tswana"]] },
  { country: "Brazil", languages: [["pt", "Português", "Portuguese"]] },
  { country: "Brunei", languages: [["ms", "Bahasa Melayu", "Malay"]] },
  { country: "Bulgaria", languages: [["bg", "Български", "Bulgarian"]] },
  { country: "Burkina Faso", languages: [["fr", "Français", "French"]] },
  { country: "Burundi", languages: [["rn", "Ikirundi", "Kirundi"], ["fr", "Français", "French"], ["en", "English", "English"]] },
  { country: "Cabo Verde", languages: [["pt", "Português", "Portuguese"]] },
  { country: "Cambodia", languages: [["km", "ខ្មែរ", "Khmer"]] },
  { country: "Cameroon", languages: [["fr", "Français", "French"], ["en", "English", "English"]] },
  { country: "Canada", languages: [["en", "English", "English"], ["fr", "Français", "French"]] },
  { country: "Central African Republic", languages: [["fr", "Français", "French"], ["sg", "Sängö", "Sango"]] },
  { country: "Chad", languages: [["fr", "Français", "French"], ["ar", "العربية", "Arabic"]] },
  { country: "Chile", languages: [["es", "Español", "Spanish"]] },
  { country: "China", languages: [["zh", "中文", "Chinese"]] },
  { country: "Colombia", languages: [["es", "Español", "Spanish"]] },
  { country: "Comoros", languages: [["ar", "العربية", "Arabic"], ["fr", "Français", "French"], ["swb", "Shikomori", "Comorian"]] },
  { country: "Congo", languages: [["fr", "Français", "French"]] },
  { country: "Costa Rica", languages: [["es", "Español", "Spanish"]] },
  { country: "Croatia", languages: [["hr", "Hrvatski", "Croatian"]] },
  { country: "Cuba", languages: [["es", "Español", "Spanish"]] },
  { country: "Cyprus", languages: [["el", "Ελληνικά", "Greek"], ["tr", "Türkçe", "Turkish"]] },
  { country: "Czechia", languages: [["cs", "Čeština", "Czech"]] },
  { country: "Democratic Republic of the Congo", languages: [["fr", "Français", "French"], ["ln", "Lingála", "Lingala"], ["kg", "Kikongo", "Kongo"], ["lua", "Tshiluba", "Tshiluba"], ["sw", "Kiswahili", "Swahili"]] },
  { country: "Denmark", languages: [["da", "Dansk", "Danish"]] },
  { country: "Djibouti", languages: [["fr", "Français", "French"], ["ar", "العربية", "Arabic"]] },
  { country: "Dominica", languages: [["en", "English", "English"]] },
  { country: "Dominican Republic", languages: [["es", "Español", "Spanish"]] },
  { country: "Ecuador", languages: [["es", "Español", "Spanish"], ["qu", "Runa Simi", "Quechua"]] },
  { country: "Egypt", languages: [["ar", "العربية", "Arabic"]] },
  { country: "El Salvador", languages: [["es", "Español", "Spanish"]] },
  { country: "Equatorial Guinea", languages: [["es", "Español", "Spanish"], ["fr", "Français", "French"], ["pt", "Português", "Portuguese"]] },
  { country: "Eritrea", languages: [["ti", "ትግርኛ", "Tigrinya"], ["ar", "العربية", "Arabic"], ["en", "English", "English"]] },
  { country: "Estonia", languages: [["et", "Eesti", "Estonian"]] },
  { country: "Eswatini", languages: [["en", "English", "English"], ["ss", "siSwati", "Swati"]] },
  { country: "Ethiopia", languages: [["am", "አማርኛ", "Amharic"], ["om", "Afaan Oromoo", "Oromo"], ["so", "Soomaali", "Somali"], ["ti", "ትግርኛ", "Tigrinya"], ["aa", "Qafaraf", "Afar"]] },
  { country: "Fiji", languages: [["en", "English", "English"], ["fj", "Na Vosa Vakaviti", "Fijian"], ["hif", "Fiji Hindi", "Fiji Hindi"]] },
  { country: "Finland", languages: [["fi", "Suomi", "Finnish"], ["sv", "Svenska", "Swedish"]] },
  { country: "France", languages: [["fr", "Français", "French"]] },
  { country: "Gabon", languages: [["fr", "Français", "French"]] },
  { country: "Gambia", languages: [["en", "English", "English"]] },
  { country: "Georgia", languages: [["ka", "ქართული", "Georgian"]] },
  { country: "Germany", languages: [["de", "Deutsch", "German"]] },
  { country: "Ghana", languages: [["en", "English", "English"]] },
  { country: "Greece", languages: [["el", "Ελληνικά", "Greek"]] },
  { country: "Grenada", languages: [["en", "English", "English"]] },
  { country: "Guatemala", languages: [["es", "Español", "Spanish"]] },
  { country: "Guinea", languages: [["fr", "Français", "French"]] },
  { country: "Guinea-Bissau", languages: [["pt", "Português", "Portuguese"]] },
  { country: "Guyana", languages: [["en", "English", "English"]] },
  { country: "Haiti", languages: [["ht", "Kreyòl ayisyen", "Haitian Creole"], ["fr", "Français", "French"]] },
  { country: "Honduras", languages: [["es", "Español", "Spanish"]] },
  { country: "Hungary", languages: [["hu", "Magyar", "Hungarian"]] },
  { country: "Iceland", languages: [["is", "Íslenska", "Icelandic"]] },
  { country: "India", languages: [["hi", "हिन्दी", "Hindi"], ["en", "English", "English"], ["bn", "বাংলা", "Bengali"], ["te", "తెలుగు", "Telugu"], ["mr", "मराठी", "Marathi"], ["ta", "தமிழ்", "Tamil"], ["gu", "ગુજરાતી", "Gujarati"], ["ur", "اردو", "Urdu"], ["kn", "ಕನ್ನಡ", "Kannada"], ["or", "ଓଡ଼ିଆ", "Odia"], ["ml", "മലയാളം", "Malayalam"], ["pa", "ਪੰਜਾਬੀ", "Punjabi"]] },
  { country: "Indonesia", languages: [["id", "Bahasa Indonesia", "Indonesian"]] },
  { country: "Iran", languages: [["fa", "فارسی", "Persian"]] },
  { country: "Iraq", languages: [["ar", "العربية", "Arabic"], ["ku", "Kurdî", "Kurdish"]] },
  { country: "Ireland", languages: [["ga", "Gaeilge", "Irish"], ["en", "English", "English"]] },
  { country: "Israel", languages: [["he", "עברית", "Hebrew"], ["ar", "العربية", "Arabic"]] },
  { country: "Italy", languages: [["it", "Italiano", "Italian"]] },
  { country: "Jamaica", languages: [["en", "English", "English"]] },
  { country: "Japan", languages: [["ja", "日本語", "Japanese"]] },
  { country: "Jordan", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Kazakhstan", languages: [["kk", "Қазақша", "Kazakh"], ["ru", "Русский", "Russian"]] },
  { country: "Kenya", languages: [["sw", "Kiswahili", "Swahili"], ["en", "English", "English"]] },
  { country: "Kiribati", languages: [["en", "English", "English"], ["gil", "Taetae ni Kiribati", "Gilbertese"]] },
  { country: "Kuwait", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Kyrgyzstan", languages: [["ky", "Кыргызча", "Kyrgyz"], ["ru", "Русский", "Russian"]] },
  { country: "Laos", languages: [["lo", "ລາວ", "Lao"]] },
  { country: "Latvia", languages: [["lv", "Latviešu", "Latvian"]] },
  { country: "Lebanon", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Lesotho", languages: [["st", "Sesotho", "Sesotho"], ["en", "English", "English"]] },
  { country: "Liberia", languages: [["en", "English", "English"]] },
  { country: "Libya", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Liechtenstein", languages: [["de", "Deutsch", "German"]] },
  { country: "Lithuania", languages: [["lt", "Lietuvių", "Lithuanian"]] },
  { country: "Luxembourg", languages: [["lb", "Lëtzebuergesch", "Luxembourgish"], ["fr", "Français", "French"], ["de", "Deutsch", "German"]] },
  { country: "Madagascar", languages: [["mg", "Malagasy", "Malagasy"], ["fr", "Français", "French"]] },
  { country: "Malawi", languages: [["en", "English", "English"], ["ny", "Chichewa", "Chichewa"]] },
  { country: "Malaysia", languages: [["ms", "Bahasa Melayu", "Malay"]] },
  { country: "Maldives", languages: [["dv", "ދިވެހި", "Dhivehi"]] },
  { country: "Mali", languages: [["fr", "Français", "French"], ["bm", "Bamanankan", "Bambara"]] },
  { country: "Malta", languages: [["mt", "Malti", "Maltese"], ["en", "English", "English"]] },
  { country: "Marshall Islands", languages: [["en", "English", "English"], ["mh", "Kajin M̧ajeļ", "Marshallese"]] },
  { country: "Mauritania", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Mauritius", languages: [["en", "English", "English"], ["fr", "Français", "French"]] },
  { country: "Mexico", languages: [["es", "Español", "Spanish"]] },
  { country: "Micronesia", languages: [["en", "English", "English"]] },
  { country: "Moldova", languages: [["ro", "Română", "Romanian"]] },
  { country: "Monaco", languages: [["fr", "Français", "French"]] },
  { country: "Mongolia", languages: [["mn", "Монгол", "Mongolian"]] },
  { country: "Montenegro", languages: [["sr", "Crnogorski", "Montenegrin"]] },
  { country: "Morocco", languages: [["ar", "العربية", "Arabic"], ["zgh", "ⵜⴰⵎⴰⵣⵉⵖⵜ", "Tamazight"]] },
  { country: "Mozambique", languages: [["pt", "Português", "Portuguese"]] },
  { country: "Myanmar", languages: [["my", "မြန်မာ", "Burmese"]] },
  { country: "Namibia", languages: [["en", "English", "English"]] },
  { country: "Nauru", languages: [["na", "Dorerin Naoero", "Nauruan"], ["en", "English", "English"]] },
  { country: "Nepal", languages: [["ne", "नेपाली", "Nepali"]] },
  { country: "Netherlands", languages: [["nl", "Nederlands", "Dutch"]] },
  { country: "New Zealand", languages: [["en", "English", "English"], ["mi", "Te Reo Māori", "Māori"]] },
  { country: "Nicaragua", languages: [["es", "Español", "Spanish"]] },
  { country: "Niger", languages: [["fr", "Français", "French"], ["ha", "Hausa", "Hausa"]] },
  { country: "Nigeria", languages: [["en", "English", "English"], ["ha", "Hausa", "Hausa"], ["yo", "Yorùbá", "Yoruba"], ["ig", "Igbo", "Igbo"]] },
  { country: "North Korea", languages: [["ko", "한국어", "Korean"]] },
  { country: "North Macedonia", languages: [["mk", "Македонски", "Macedonian"], ["sq", "Shqip", "Albanian"]] },
  { country: "Norway", languages: [["no", "Norsk", "Norwegian"]] },
  { country: "Oman", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Pakistan", languages: [["ur", "اردو", "Urdu"], ["en", "English", "English"]] },
  { country: "Palau", languages: [["en", "English", "English"], ["pau", "a tekoi er a Belau", "Palauan"]] },
  { country: "Palestine", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Panama", languages: [["es", "Español", "Spanish"]] },
  { country: "Papua New Guinea", languages: [["en", "English", "English"], ["tpi", "Tok Pisin", "Tok Pisin"], ["ho", "Hiri Motu", "Hiri Motu"]] },
  { country: "Paraguay", languages: [["es", "Español", "Spanish"], ["gn", "Avañe’ẽ", "Guarani"]] },
  { country: "Peru", languages: [["es", "Español", "Spanish"], ["qu", "Runa Simi", "Quechua"], ["ay", "Aymar aru", "Aymara"]] },
  { country: "Philippines", languages: [["fil", "Filipino", "Filipino"], ["en", "English", "English"]] },
  { country: "Poland", languages: [["pl", "Polski", "Polish"]] },
  { country: "Portugal", languages: [["pt", "Português", "Portuguese"]] },
  { country: "Qatar", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Romania", languages: [["ro", "Română", "Romanian"]] },
  { country: "Russia", languages: [["ru", "Русский", "Russian"]] },
  { country: "Rwanda", languages: [["rw", "Ikinyarwanda", "Kinyarwanda"], ["en", "English", "English"], ["fr", "Français", "French"], ["sw", "Kiswahili", "Swahili"]] },
  { country: "Saint Kitts and Nevis", languages: [["en", "English", "English"]] },
  { country: "Saint Lucia", languages: [["en", "English", "English"]] },
  { country: "Saint Vincent and the Grenadines", languages: [["en", "English", "English"]] },
  { country: "Samoa", languages: [["sm", "Gagana Samoa", "Samoan"], ["en", "English", "English"]] },
  { country: "San Marino", languages: [["it", "Italiano", "Italian"]] },
  { country: "Sao Tome and Principe", languages: [["pt", "Português", "Portuguese"]] },
  { country: "Saudi Arabia", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Senegal", languages: [["fr", "Français", "French"], ["wo", "Wolof", "Wolof"]] },
  { country: "Serbia", languages: [["sr", "Српски", "Serbian"]] },
  { country: "Seychelles", languages: [["en", "English", "English"], ["fr", "Français", "French"], ["crs", "Seselwa", "Seychellois Creole"]] },
  { country: "Sierra Leone", languages: [["en", "English", "English"]] },
  { country: "Singapore", languages: [["en", "English", "English"], ["ms", "Bahasa Melayu", "Malay"], ["zh", "中文", "Chinese"], ["ta", "தமிழ்", "Tamil"]] },
  { country: "Slovakia", languages: [["sk", "Slovenčina", "Slovak"]] },
  { country: "Slovenia", languages: [["sl", "Slovenščina", "Slovenian"]] },
  { country: "Solomon Islands", languages: [["en", "English", "English"]] },
  { country: "Somalia", languages: [["so", "Soomaali", "Somali"], ["ar", "العربية", "Arabic"]] },
  { country: "South Africa", languages: [["af", "Afrikaans", "Afrikaans"], ["en", "English", "English"], ["nr", "isiNdebele", "Southern Ndebele"], ["nso", "Sesotho sa Leboa", "Northern Sotho"], ["st", "Sesotho", "Sesotho"], ["ss", "siSwati", "Swati"], ["tn", "Setswana", "Tswana"], ["ts", "Xitsonga", "Tsonga"], ["ve", "Tshivenḓa", "Venda"], ["xh", "isiXhosa", "Xhosa"], ["zu", "isiZulu", "Zulu"]] },
  { country: "South Korea", languages: [["ko", "한국어", "Korean"]] },
  { country: "South Sudan", languages: [["en", "English", "English"]] },
  { country: "Spain", languages: [["es", "Español", "Spanish"], ["ca", "Català", "Catalan"], ["eu", "Euskara", "Basque"], ["gl", "Galego", "Galician"]] },
  { country: "Sri Lanka", languages: [["si", "සිංහල", "Sinhala"], ["ta", "தமிழ்", "Tamil"]] },
  { country: "Sudan", languages: [["ar", "العربية", "Arabic"], ["en", "English", "English"]] },
  { country: "Suriname", languages: [["nl", "Nederlands", "Dutch"]] },
  { country: "Sweden", languages: [["sv", "Svenska", "Swedish"]] },
  { country: "Switzerland", languages: [["de", "Deutsch", "German"], ["fr", "Français", "French"], ["it", "Italiano", "Italian"], ["rm", "Rumantsch", "Romansh"]] },
  { country: "Syria", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Taiwan", languages: [["zh", "中文", "Chinese"]] },
  { country: "Tajikistan", languages: [["tg", "Тоҷикӣ", "Tajik"]] },
  { country: "Tanzania", languages: [["sw", "Kiswahili", "Swahili"], ["en", "English", "English"]] },
  { country: "Thailand", languages: [["th", "ไทย", "Thai"]] },
  { country: "Timor-Leste", languages: [["tet", "Tetun", "Tetum"], ["pt", "Português", "Portuguese"]] },
  { country: "Togo", languages: [["fr", "Français", "French"]] },
  { country: "Tonga", languages: [["to", "Lea faka-Tonga", "Tongan"], ["en", "English", "English"]] },
  { country: "Trinidad and Tobago", languages: [["en", "English", "English"]] },
  { country: "Tunisia", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Turkey", languages: [["tr", "Türkçe", "Turkish"]] },
  { country: "Turkmenistan", languages: [["tk", "Türkmençe", "Turkmen"]] },
  { country: "Tuvalu", languages: [["tvl", "Te Ggana Tuuvalu", "Tuvaluan"], ["en", "English", "English"]] },
  { country: "Uganda", languages: [["en", "English", "English"], ["sw", "Kiswahili", "Swahili"]] },
  { country: "Ukraine", languages: [["uk", "Українська", "Ukrainian"]] },
  { country: "United Arab Emirates", languages: [["ar", "العربية", "Arabic"]] },
  { country: "United Kingdom", languages: [["en", "English", "English"], ["cy", "Cymraeg", "Welsh"], ["gd", "Gàidhlig", "Scottish Gaelic"]] },
  { country: "United States", languages: [["en", "English", "English"]] },
  { country: "Uruguay", languages: [["es", "Español", "Spanish"]] },
  { country: "Uzbekistan", languages: [["uz", "Oʻzbekcha", "Uzbek"]] },
  { country: "Vanuatu", languages: [["bi", "Bislama", "Bislama"], ["en", "English", "English"], ["fr", "Français", "French"]] },
  { country: "Vatican City", languages: [["it", "Italiano", "Italian"], ["la", "Latina", "Latin"]] },
  { country: "Venezuela", languages: [["es", "Español", "Spanish"]] },
  { country: "Vietnam", languages: [["vi", "Tiếng Việt", "Vietnamese"]] },
  { country: "Yemen", languages: [["ar", "العربية", "Arabic"]] },
  { country: "Zambia", languages: [["en", "English", "English"]] },
  { country: "Zimbabwe", languages: [["en", "English", "English"], ["sn", "chiShona", "Shona"], ["nd", "isiNdebele", "Northern Ndebele"]] },
];

const RTL_LANGS = new Set(["ar", "fa", "he", "ur", "ps", "dv", "yi", "ug", "ckb", "sd"]);
